// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.gongdao.zq;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gongdao.zq.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
