# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/main/java/com/protobuf/Student.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/main/java/com/protobuf/Student.proto',
  package='com.protobuf',
  syntax='proto2',
  serialized_pb=_b('\n(src/main/java/com/protobuf/Student.proto\x12\x0c\x63om.protobuf\"\xed\x01\n\tMyMessage\x12\x32\n\x08\x64\x61teType\x18\x01 \x02(\x0e\x32 .com.protobuf.MyMessage.DataType\x12&\n\x06person\x18\x02 \x01(\x0b\x32\x14.com.protobuf.PersonH\x00\x12 \n\x03\x64og\x18\x03 \x01(\x0b\x32\x11.com.protobuf.DogH\x00\x12 \n\x03\x63\x61t\x18\x04 \x01(\x0b\x32\x11.com.protobuf.CatH\x00\"4\n\x08\x44\x61taType\x12\x0e\n\nPersonType\x10\x01\x12\x0b\n\x07\x44ogType\x10\x02\x12\x0b\n\x07\x43\x61tType\x10\x03\x42\n\n\x08\x64\x61tabody\"4\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\"&\n\x03\x44og\x12\r\n\x05name1\x18\x01 \x01(\t\x12\x10\n\x08\x61\x64\x64ress1\x18\x02 \x01(\t\"&\n\x03\x43\x61t\x12\r\n\x05name2\x18\x02 \x01(\t\x12\x10\n\x08\x61\x64\x64ress2\x18\x03 \x01(\tB$\n\x15\x63om.gongdao.protobuf1B\x0bMyDataInfo1')
)



_MYMESSAGE_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='com.protobuf.MyMessage.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PersonType', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DogType', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CatType', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=232,
  serialized_end=284,
)
_sym_db.RegisterEnumDescriptor(_MYMESSAGE_DATATYPE)


_MYMESSAGE = _descriptor.Descriptor(
  name='MyMessage',
  full_name='com.protobuf.MyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dateType', full_name='com.protobuf.MyMessage.dateType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='person', full_name='com.protobuf.MyMessage.person', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dog', full_name='com.protobuf.MyMessage.dog', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cat', full_name='com.protobuf.MyMessage.cat', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MYMESSAGE_DATATYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='databody', full_name='com.protobuf.MyMessage.databody',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=59,
  serialized_end=296,
)


_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='com.protobuf.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.protobuf.Person.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='age', full_name='com.protobuf.Person.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='com.protobuf.Person.address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=350,
)


_DOG = _descriptor.Descriptor(
  name='Dog',
  full_name='com.protobuf.Dog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name1', full_name='com.protobuf.Dog.name1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address1', full_name='com.protobuf.Dog.address1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=390,
)


_CAT = _descriptor.Descriptor(
  name='Cat',
  full_name='com.protobuf.Cat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name2', full_name='com.protobuf.Cat.name2', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address2', full_name='com.protobuf.Cat.address2', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=430,
)

_MYMESSAGE.fields_by_name['dateType'].enum_type = _MYMESSAGE_DATATYPE
_MYMESSAGE.fields_by_name['person'].message_type = _PERSON
_MYMESSAGE.fields_by_name['dog'].message_type = _DOG
_MYMESSAGE.fields_by_name['cat'].message_type = _CAT
_MYMESSAGE_DATATYPE.containing_type = _MYMESSAGE
_MYMESSAGE.oneofs_by_name['databody'].fields.append(
  _MYMESSAGE.fields_by_name['person'])
_MYMESSAGE.fields_by_name['person'].containing_oneof = _MYMESSAGE.oneofs_by_name['databody']
_MYMESSAGE.oneofs_by_name['databody'].fields.append(
  _MYMESSAGE.fields_by_name['dog'])
_MYMESSAGE.fields_by_name['dog'].containing_oneof = _MYMESSAGE.oneofs_by_name['databody']
_MYMESSAGE.oneofs_by_name['databody'].fields.append(
  _MYMESSAGE.fields_by_name['cat'])
_MYMESSAGE.fields_by_name['cat'].containing_oneof = _MYMESSAGE.oneofs_by_name['databody']
DESCRIPTOR.message_types_by_name['MyMessage'] = _MYMESSAGE
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['Dog'] = _DOG
DESCRIPTOR.message_types_by_name['Cat'] = _CAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyMessage = _reflection.GeneratedProtocolMessageType('MyMessage', (_message.Message,), dict(
  DESCRIPTOR = _MYMESSAGE,
  __module__ = 'src.main.java.com.protobuf.Student_pb2'
  # @@protoc_insertion_point(class_scope:com.protobuf.MyMessage)
  ))
_sym_db.RegisterMessage(MyMessage)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(
  DESCRIPTOR = _PERSON,
  __module__ = 'src.main.java.com.protobuf.Student_pb2'
  # @@protoc_insertion_point(class_scope:com.protobuf.Person)
  ))
_sym_db.RegisterMessage(Person)

Dog = _reflection.GeneratedProtocolMessageType('Dog', (_message.Message,), dict(
  DESCRIPTOR = _DOG,
  __module__ = 'src.main.java.com.protobuf.Student_pb2'
  # @@protoc_insertion_point(class_scope:com.protobuf.Dog)
  ))
_sym_db.RegisterMessage(Dog)

Cat = _reflection.GeneratedProtocolMessageType('Cat', (_message.Message,), dict(
  DESCRIPTOR = _CAT,
  __module__ = 'src.main.java.com.protobuf.Student_pb2'
  # @@protoc_insertion_point(class_scope:com.protobuf.Cat)
  ))
_sym_db.RegisterMessage(Cat)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025com.gongdao.protobuf1B\013MyDataInfo1'))
# @@protoc_insertion_point(module_scope)
