// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.zq1.zq;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.zq.zq.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
