// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.zq1.zq;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.zq.zq.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 2;</code>
   */
  String getRealname();
  /**
   * <code>string realname = 2;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
